### ISSUE TITLE
'bool' object is not callable in Django 2.0.2

### ISSUE THREAD

**Issue by mayait** [catcombo/django-speedinfo#1]
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/Users/juli/dev/leansew/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/juli/dev/leansew/env/lib/python3.6/site-packages/speedinfo/middleware.py", line 112, in __call__
    return self.process_response(request, response)
  File "/Users/juli/dev/leansew/env/lib/python3.6/site-packages/speedinfo/middleware.py", line 90, in process_response
    is_anon_call = request.user.is_anonymous()
TypeError: 'bool' object is not callable

**Comment by mayait** [comment]
I'm aware that _"Using User.is_authenticated() and User.is_anonymous() as methods rather than properties is no longer supported."_ but I don't know where to fix it.

**Comment by mayait** [comment]
Fix in line 90: speedinfo/backends
`is_anon_call = request.user.is_anonymous`

**Comment by catcombo** [comment]
@mayait Hey Julian! Sorry for delay. Thank you for the bug report. Fixed in 1.3.1 release.

**Comment by vikraman-melorra** [comment]
is_anon_call = request.user.is_anonymous
its useful one thanks
