### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by ChillarAnand** [catcombo/django-speedinfo#6]
I have installed speedinfo on a [test project](https://github.com/chillarAnand/library). Initially it was throwing an error

```
Traceback (most recent call last):
  File "/Users/curatech/.virtualenvs/library/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/curatech/.virtualenvs/library/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "/Users/curatech/.virtualenvs/library/lib/python3.7/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/Users/curatech/.virtualenvs/library/lib/python3.7/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/curatech/.virtualenvs/library/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/curatech/.virtualenvs/library/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/curatech/.virtualenvs/library/lib/python3.7/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/Users/curatech/.virtualenvs/library/lib/python3.7/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/Users/curatech/.virtualenvs/library/lib/python3.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/curatech/.virtualenvs/library/lib/python3.7/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/Users/curatech/.virtualenvs/library/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/curatech/.virtualenvs/library/lib/python3.7/site-packages/speedinfo/admin.py", line 132, in <module>
    admin.site.register(ViewProfiler, ViewProfilerAdmin)
  File "/Users/curatech/.virtualenvs/library/lib/python3.7/site-packages/django/contrib/admin/sites.py", line 109, in register
    raise AlreadyRegistered('The model %s is already registered' % model.__name__)
django.contrib.admin.sites.AlreadyRegistered: The model ViewProfiler is already registered
```

To prevent this, I have unregistered model.

```
from speedinfo.models import ViewProfiler

admin.site.unregister(ViewProfiler)
```

After this, setup was completed. I have browsed several pages on the app with toggle on and off but nothing is showing up in admin panel of speedinfo. Should I add any additional code to track the views?

<img width="1280" alt="Screen Shot 2019-06-12 at 10 13 47 PM" src="https://user-images.githubusercontent.com/4463796/59370123-80926c80-8d5f-11e9-91ad-4d5743028f1e.png">

```

**Comment by catcombo** [comment]
@ChillarAnand That was an interesting case :) The problem is in [this loop](https://github.com/ChillarAnand/library/blob/master/book/admin.py#L71) in `book/admin.py`:

```
models = apps.get_models()
for model in models:
    admin_class = type('AdminClass', (ListAdminMixin, admin.ModelAdmin), {})
    try:
        admin.site.register(model, admin_class)
    except admin.sites.AlreadyRegistered:
        pass
```
Here you get the model `speedinfo.models.ViewProfiler` and register admin class for it. Then Django tries to register the model second time in `speedinfo.admin` where you got the error. I comment out the loop and error disappears.

**Comment by ChillarAnand** [comment]
Thanks @catcombo 

Does speedinfo automatically profile all the views or do we have to set up any hooks?

**Comment by catcombo** [comment]
@ChillarAnand `speedinfo` profiles all views by default, but you can customize the behaviour by providing `SPEEDINFO_EXCLUDE_URLS` or [write custom profiling condition](https://github.com/catcombo/django-speedinfo#profiling-conditions).

**Comment by ChillarAnand** [comment]
@catcombo I have set it up as per https://github.com/catcombo/django-speedinfo#installation. It created a cache file at /tmp/django_cache/c53e40b02d369922232dca8eecbb3fd9.djcache but in admin nothing is showing up after browsing multiple pages. Any suggestions on what can be wrong?

**Comment by catcombo** [comment]
@ChillarAnand Uncomment [this line](https://github.com/ChillarAnand/library/blob/master/library/settings/dev.py#L38) :)

**Comment by ChillarAnand** [comment]
My bad :)

May be a simple check can be added to prevent this. Debug toolbar includes an error message.

```
ERRORS:
?: debug_toolbar.middleware.DebugToolbarMiddleware is missing from MIDDLEWARE.
        HINT: Add debug_toolbar.middleware.DebugToolbarMiddleware to MIDDLEWARE.
```

Thanks @catcombo
